### ISSUE TITLE
Tracking: Improving FDE content.

### ISSUE THREAD

**Issue by flexibeast** [void-linux/void-docs#492]
This issue consolidates #284, #375, #398 and #432. Further requests for corrections / improvements to FDE-related content should be made here, until all outstanding issues have been resolved.

- [ ] Refactor "Full Disk Encryption" section (#284)
- [ ] Add information regarding swap(/files) and hibernation in Full Disk Encryption (#375)
- [ ] FDE + EFI reworking (#398)
- [ ] Clarify what steps need to be taken to enable TRIM on an FDE setup (#432)

i'll close #284, #375, #398 and #432 as superseded by this issue, but of course, the discussions in those issues should still be referred to.

cc: @Kratacoa, @brihadeesh, @cinerea0

**Comment by Kratacoa** [comment]
In case it may be useful, I have documented my installation in [this gist](https://gist.github.com/Kratacoa/95b1cce529afe8a2747ab7d74923be31), using BTRFS + swapfile encryption.  
However, it is an incomplete guide (it is missing secure boot and proper SSD configuration).  
I may contribute once I inquire again into it and have a clearer idea of what's going on.

**Comment by goc980** [comment]
I would like to see a guide added that does not encrypt /boot, but only encrypts /.
